# This is just a sample codecov config -- feel free to modify however you like so that it fits the unique setup of yours.
# N.B. Apparently, this file must be named `codecov.yml`, without the leading dot...

codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "90...100"
  status:
    project: yes
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no
